batch_size: 1
num_epochs1: 20
num_epochs2: 30
num_epochs3: 20
lr1: 3e-4
lr2: 2e-4
lr3: 2e-4
report_interval: 10
net_name: 'promptmr_wide_fd_wc'
data_path_train: '/home/Data/train/'
data_path_val: '/home/Data/val/'
model: 'promptmr'
sens_model: 'promptmr'
step_size: 2
full_data: true
crop_by_width: true
milestones1: [10, 13, 16, 18]
milestones2: [10, 14, 18, 22, 26]
milestones3: [10, 13, 15, 17, 18]
clip_norm: 10
gamma: 0.4
aug_on: true
mask_type: 'equi'
output_target_key: 'image'
gpu_id: 0
aug_delay: 3
sens_chans: 3
sens_num_layers: 4
cascade1: 5
chans1: 1
num_layers1: 4
cascade2: 6
chans2: 6
num_layers2: 5
cascade3: 6
chans3: 5
num_layers3: 5
aug_strength: 0.55
aug_exp_decay: 5.0
aug_weight_translation: 0.0
aug_weight_rotation: 0.0
aug_weight_scaling: 1.0
aug_weight_shearing: 0.0
aug_weight_rot90: 0.5
aug_weight_fliph: 0.5
aug_weight_flipv: 0.5
aug_max_translation_x: 0.05
aug_max_translation_y: 0.75
aug_max_rotation: 180
aug_max_shearing_x: 6.25
aug_max_shearing_y: 6.25
aug_max_scaling: 0.25
